# Site settings
gems: [jekyll-paginate]

# Dependencies
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ['strikethrough']

kramdown:
  input: GFM

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: Reactive Spaces and Media Architecture
tagline: 'CMU - Fall 2019'
description: 'Project-based course for exploring large scale dynamic media in the built environment.'
--url: 'http://jmarsico.github.io/rsma2019'
--baseurl: 'http://jmarsico.github.io/rsma2019'
baseurl: '/rsma2019'

author:
  name: 'Jakob Marsico'
  url: http://jmarsico.github.io/rsma2019/

email: jmarsico@gmail.com
twitter_username: n/a
github_username: jmarsico
slack: http://rsma2019.slack.com
gallery: http://ideate.xsead.cmu.edu
facilities: https://resources.ideate.cmu.edu/

paginate: 5

# Custom vars
version: 1.0.5

github:
  repo: https://github.com/jmarsico/rsma2019
